# My variables
name: Justin Smith
description: Cryptofinance technologist and experienced entrepreneur.
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

#baseurl: /website-personal
baseurl: /jsmith 

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
